### ISSUE TITLE
Unable to get it working on IE8

### ISSUE THREAD

**Issue by tducasse** [lndb/jsPlumb_Liviz.js#2]
I have multiple errors, and I don't see the arrows !
Here are the errors : 
Détails de l’erreur de la page Web

Agent utilisateur : Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; MS-RTC LM 8)
Horodateur : Fri, 24 Apr 2015 11:34:27 UTC

Message : Cet objet ne gère pas cette propriété ou cette méthode
Ligne : 4
Caractère : 6105
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jquery/jquery-2.0.2.min.js

Message : 'jQuery' est indéfini.
Ligne : 6
Caractère : 1
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jquery/jquery-ui-1.10.3.custom.min.js

Message : 'jQuery' est indéfini.
Ligne : 17
Caractère : 9
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jquery/jquery.ui.touch-punch.js

Message : 'jQuery' est indéfini.
Ligne : 1
Caractère : 140039
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jsPlumb/jquery.jsPlumb-1.4.1-all-min.js

Message : Objet attendu
Ligne : 162
Caractère : 5
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jsPlumbChar.htm

Message : Valeur de propriété non valide.
Ligne : 12
Caractère : 3
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/Liviz.js/progress-view.js?v=2

Message : Cet objet ne gère pas cette propriété ou cette méthode
Ligne : 129
Caractère : 1
Code : 0
URI : file:///C:/Users/A601926/Downloads/jsPlumb_Liviz.js-master/jsPlumb_Liviz.js-master/jsPlumbChar.htm

It's french, but basically, it's  "JQuery is undefined" and "This object can't handle this property or method" approximately.

I saw that you use jquery 2+ ? Isn't that supposed to be only for browsers >IE9 ?
Do you have any idea about how I can make it work ?

**Comment by lndb** [comment]
You can easily replace jQuery 2 with jQuery 1.x, but if I remember right, Javascript Web Workers, don't work in IE8 and 9.

Edit:
http://caniuse.com/#feat=webworkers

**Comment by tducasse** [comment]
That's what I was thinking. Thanks for taking the time to answer.
